apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit
spec:
  selector:
    matchLabels:
      app: credit
  replicas: 1
  template:
    metadata:
      labels:
        app: credit
    spec:
      containers:
      - name: credit
        image: 4600f5340b97
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"            
          limits:
            memory: 512
            cpu: 512
        ports:
        - containerPort: 9696